### ISSUE TITLE
develop using py3

### ISSUE THREAD

**Issue by satra** [incf-nidash/PyNIDM#1]
@dbkeator - shall we develop with python 3 and anybody who is interested can support python 2?

**Comment by vsoch** [comment]
I would by default do python 3 and add support for 2 when someone complains about it :) Is this round 2 for the nidm-api?

**Comment by satra** [comment]
yes this is round 2.

**Comment by vsoch** [comment]
ok, let me know if I can help. Do you guys use a slack or something similar, or just communicate via Github issues?

**Comment by cmaumet** [comment]
+1 to use Python3 and work on compatibility with Python2 
@vsoch: not yet but we could create a channel under the brainhack slack! What do others think?

**Comment by satra** [comment]
slack channel here: https://brainhack.slack.com/messages/C7G0AN8Q0

api discussion here #30
