### ISSUE TITLE
tests for GetProjectsComputedMetadata

### ISSUE THREAD

**Issue by dbkeator** [incf-nidash/PyNIDM#132]
@albertcrowley 

We should discuss one of the tests for GetProjectsComputedMetadata.  It isn't returning correct results and I'm fairly sure I know why but maybe a quick hangout is better to explain.
See:
[](https://github.com/incf-nidash/PyNIDM/blob/e8edc298f88f9c98a67ed5006953f746ff7aac65/nidm/experiment/tests/test_query.py#L236)

In brief, the current query depends on the Project activity UUID which isn't guaranteed to remain consistent in the simple2 ReproNim commits...there's also a problem with retrieving age but I'm not entirely sure why that's happening...

**Comment by albertcrowley** [comment]
Thanks for double checking me on this.  I'm working on my SRT project today
so I can't do a hangout this afternoon.  I'll take a look at these tests
tomorrow. I'm not sure if you are traveling back from the Repronim EAB
tomorrow, but I'm free in the afternoon if you want to talk sometime after
1pm Eastern.

**Comment by albertcrowley** [comment]
Sorry, I didn't see the context for this when I wrote my message last week.  I thought you were commenting on one of my pull requests from last week.  This is actually regarding this old bug.

So I'm all set on this and don't have any questions.
