### ISSUE TITLE
DWI datatype fails with newer versions of pybids

### ISSUE THREAD

**Issue by JayHennessy** [incf-nidash/PyNIDM#159]
After pybids 0.7 you can no longer access entities as attributes.
So, on line 508 and 509 of BIDSMRI2NIDM.py the lines:

(508) if 'run' in file_tpl._fields:
(509)     acq_obj.add_attributes({BIDS_Constants.json_keys["run"]:file_tpl.run})

Should be:
if 'run' in file_tpl.entities:
    acq_obj.add_attributes({BIDS_Constants.json_keys["run"]:file_tpl. entities[‘run’]})

**Comment by dbkeator** [comment]
Thanks...this should be fixed in the latest commits...
