### ISSUE TITLE
Add git-annex sources to bidsmri2nidm 

### ISSUE THREAD

**Issue by dbkeator** [incf-nidash/PyNIDM#182]
When converting BIDS datasets provided through datalad, multiple prov:atLocation sources can be extracted from "git annex info" command about remotes hashes of clones...see git show git-annex:remote.log...cat .datalad/config gies the unique ID of the datalad dataset...can in the future ask datalad if it has this UUID...

**Comment by dbkeator** [comment]
How do we store local location vs. datalad / git-annex locations in AcquisitionObjects?

**Comment by dbkeator** [comment]
Could use datalad:Location for datalad/git-annex source locations....

**Comment by dbkeator** [comment]
My current draft implementation:

1. Gets git annex / datalad sources if they exist with predicate datalad::Location
2. If they don't exist then a local file path is used with predicate prov:Location
3. Since git annex / datalad doesn't return a source for the BIDS root directory it's stored as a local source with prov:Location

Example:

niiri:e9acdaa8-478f-11ea-885c-003ee1ce9545 a nidm:AcquisitionObject,
        prov:Entity ;
    **datalad:Location "http://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Peking_2/sub-8278680/ses-1/anat/sub-8278680_ses-1_run-1_T1w.nii.gz?versionId=a3h6MSCqG2TzsGeiYJsR_b.cLdBlzmPM"^^xsd:string ;**
**nfo:filename "/sub-8278680/ses-1/anat/sub-8278680_ses-1_run-1_T1w.nii.gz"^^xsd:string ;**

niiri:bff384c8-478f-11ea-885c-003ee1ce9545 a nidm:Project,
        prov:Activity ;
    dctypes:title "ADHD200 - Peking_2"^^xsd:string ;
    sio:Identifier 1.2e+00 ;
    dcat:author "Yu-feng WangYu-feng ZangLi SunQing-jiu CaoLi An"^^xsd:string ;
    **prov:Location "file://datasets.datalad.org/adhd200/RawDataBIDS/Peking_2"^^xsd:string .**

**Comment by satra** [comment]
but this: `datalad:Location "http://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Peking_2/sub-8278680/ses-1/anat/sub-8278680_ses-1_run-1_T1w.nii.gz?versionId=a3h6MSCqG2TzsGeiYJsR_b.cLdBlzmPM"^^xsd:string ;`

is not a datalad location. it's a `prov:atLocation` for that entity.

**Comment by dbkeator** [comment]
@satra Ok so we're just going with prov:Location for these URIs...what about the nfo:filename bit and the prov:Location in Project?  I'd like to only do this one more time...but I'm sure that's just a dream.
