### ISSUE TITLE
add Etelemetry to tools

### ISSUE THREAD

**Issue by dbkeator** [incf-nidash/PyNIDM#183]
Etelemetry software service to track usage....add to csv2nidm, bids2nidm, and probably the API in general.  Query ReproNim about adding this

**Comment by dbkeator** [comment]
https://github.com/sensein/etelemetry-server

**Comment by dbkeator** [comment]
https://github.com/sensein/etelemetry-client

**Comment by satra** [comment]
added via #222 and ddcd4f3038
