### ISSUE TITLE
additional types serialized as Literals by provtoolbox?

### ISSUE THREAD

**Issue by dbkeator** [incf-nidash/PyNIDM#20]
Hey @satra,
In the NIDM-Exp API, when adding additional prov:types using the add_attributes function of provtoolbox, the additional rdf:types get serialized as Literals of type ^^xsd:string instead of URIs.  Any idea how to change this?  It makes querying the document for nidm:Project information quite challenging...

Here's an example: [https://github.com/incf-nidash/PyNIDM/blob/master/nidm/experiment/tools/ds000030_single_subj.ttl#L31](url)

Code that added this rdf:type is here:
[https://github.com/incf-nidash/PyNIDM/blob/master/nidm/experiment/Project.py#L45](url)

**Comment by satra** [comment]
@dbkeator: the reason for this is that `Constants.NIDM_PROJECT` is not a `QualifiedName`

```python
In [27]: doc = pm.ProvDocument()
In [28]: a1 = doc.activity(pm.QualifiedName(pm.Namespace("nidm", C.NIDM), Core().getUUID()))
In [29]: a1.add_attributes({pm.PROV_TYPE: C.NIDM_PROJECT})
In [30]: a1.add_attributes({pm.PROV_TYPE: pm.QualifiedName(pm.Namespace("nidm", C.NIDM), 'Project')})
In [31]: print(doc.get_provn())
document
  prefix nidm <http://purl.org/nidash/nidm#>
  
  activity(nidm:d3735136-a9f8-11e7-bd3b-985aeb8aa27e, -, -, [prov:type="http://purl.org/nidash/nidm#Project", prov:type='nidm:Project'])
endDocument
```

**Comment by satra** [comment]
btw, `getUUID()` should just be a standalone function, doesn't have to be part of the `Core` class, since that method makes no use of `self`.

**Comment by dbkeator** [comment]
Ah, I see.  That's an issue I should deal with in the Constants file.  It's a holdover from using RDFLib where I'm not setting those constants up as provtoolbox qualified names from the get go.  Maybe I should just do that now with all the NIDM-Exp namespaces since NIDM-Results work isn't happening in PyNIDM at this point and when it does it'll likely be coupled with migrating from RDFLib to provtoolbox.  What do you think?

Next commit will move the getUUID function out of the Core class...thanks for the suggestion
