### ISSUE TITLE
replace fuzzywuzzy with rapidfuzz

### ISSUE THREAD

**Issue by satra** [incf-nidash/PyNIDM#234]
because of fuzzywuzzy's change in license, we should remove our dependence on it and replace with rapidfuzz (https://github.com/maxbachmann/rapidfuzz).

when i first used fuzzwuzzy, it was under MIT license and then they switched to GPL, because the levenshtein distance code they were using was marked GPL-2. we did not pay attention to this, and hence should remove it now.

**Comment by dbkeator** [comment]
Done...

[https://github.com/incf-nidash/PyNIDM/pull/235](url)
