### ISSUE TITLE
Permission denied when trying to open git annexed file

### ISSUE THREAD

**Issue by JayHennessy** [incf-nidash/PyNIDM#251]
In the function /nidm/experiment/Utils/ map_variables_to_terms.py (line 905) the function tries to read the source json with mode "r+" but this is causing a permission denied error with my dataladed dataset since the files are locked.

I think if this is changed to "r" instead of "r+" it should fix the issue. We don't need to write to the file at this point anyway.

Best,
Jay

**Comment by dbkeator** [comment]
Thanks for the bug report and suggested fix.  This has been fixed in the latest version (v3.7..3)
