### ISSUE TITLE
NIDM data structure as JSON-LD?

### ISSUE THREAD

**Issue by mih** [incf-nidash/PyNIDM#60]
Is there a way to get the output of BIDS2NIDM as JSON-LD? ATM turtle is hard-coded, and I cannot see something in the Python API that would allow me to do all of what this tool does, but then serialize to something else.

I do not need a file in JSON-LD, the corresponding runtime data structure would be sufficient, and actually more useful.

Thanks!

**Comment by dbkeator** [comment]
Yes, we have a function for that [https://github.com/incf-nidash/PyNIDM/blob/master/nidm/experiment/Core.py#L301](url).  Will add a parameter to BIDSMRI2NIDM to export JSON-LD

**Comment by mih** [comment]
Thanks @dbkeator. I managed to get a JSON-LD file dump for my test dataset after doing some manual fixing and editing.

It would be nice to be able to use just the Python API to get a runtime representation of this graph without having to use intermediate temporary files. Is this possible too?

**Comment by dbkeator** [comment]
BIDSMRI2NIDM.py now includes command line switch "-jsonld" to export JSON-LD

**Comment by satra** [comment]
we should add a prov context to the json-ld serialization.

**Comment by satra** [comment]
here is a basic one to start with:

```
    "@context": {
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "prov": "http://www.w3.org/ns/prov#",
        "foaf": "http://xmlns.com/foaf/0.1/",

        "agent": { "@type": "@id", "@id": "prov:agent" },
        "entity": { "@type": "@id", "@id": "prov:entity" },
        "activity": { "@type": "@id", "@id": "prov:activity" },
        "hadPlan": { "@type": "@id", "@id": "prov:hadPlan" },
        "hadRole": { "@type": "@id", "@id": "prov:hadRole" },
        "wasAttributedTo": { "@type": "@id", "@id": "prov:wasAttributedTo" },
        "association": { "@type": "@id", "@id": "prov:qualifiedAssociation" },
        "usage": { "@type": "@id", "@id": "prov:qualifiedUsage" },
        "generation": { "@type": "@id", "@id": "prov:qualifiedGeneration" },

        "startedAtTime": { "@type": "xsd:dateTime", "@id": "prov:startedAtTime" },
        "endedAtTime": { "@type": "xsd:dateTime", "@id": "prov:endedAtTime" },

        "@base": "http://mobyle.pasteur.fr/data/jobs/blast2/X07109667685986/"
    },
```
