### ISSUE TITLE
Please release/upload to pypi

### ISSUE THREAD

**Issue by yarikoptic** [incf-nidash/PyNIDM#67]
as this beast to be used within datalad now, it would be nice to have it released and versioned
Note , that currently
```
$> python -c 'import nidm; print nidm.__version__'
0.1.dev
```
so released version should be `0.1.1` or `0.2`.

ideally also would be great to see a conda package, and we will take care about neurodebian ;)

**Comment by satra** [comment]
@yarikoptic - we need to clean up a few things before a release, but let's target end of april for a release.

**Comment by satra** [comment]
this is now uploading via manual push but release needs to happen through github process (see #244)
