### ISSUE TITLE
py2 support

### ISSUE THREAD

**Issue by djarecka** [incf-nidash/PyNIDM#77]
do we want to keep the py2 support?

**Comment by sanuann** [comment]
I think the six library does it - support codebases that work on both Python 2 and 3 without modification.

**Comment by satra** [comment]
no - we decided pynidm would be py3 only. #1

**Comment by djarecka** [comment]
oh, ok. so we should remove py2 from travis...

**Comment by khelm** [comment]
What's the reason for not supporting python2?

**Comment by satra** [comment]
@khelm - see initial discussion here #1 

but in general the community is moving away from trying to maintain multiple code bases. we are already quite resource constrained. all python development is happening in py3. in fact, some of the features in py36/37 moves away even from earlier versions of py3.

**Comment by satra** [comment]
and by community i meant the broader python and scientific python community.

**Comment by khelm** [comment]
I would disagree that "all python development is happening in py3", but I get the resource constraint issue.
Thanks.

**Comment by satra** [comment]
@khelm - python team is not doing any development on py27. when i mean python development, i meant core python, not the ecosystem around.

**Comment by djarecka** [comment]
Jan 2020 is coming quickly: https://python3statement.org/
