### ISSUE TITLE
using owl files from nidm-specs

### ISSUE THREAD

**Issue by djarecka** [incf-nidash/PyNIDM#94]
we should remove owl files from `term` and using the one from nidm-specs repo directly

**Comment by dbkeator** [comment]
This may be a problem for @khelm because I've simply been using the copies of the OWL files that are in PyNIDM....

**Comment by khelm** [comment]
@djarecka - I don't think those demographics files are being used for anything and are legacy files.  @cmaumet - is this true?  I believe that you just need the nidm-experiment.owl files and the files in .../nidm-experiment/imports

**Comment by djarecka** [comment]
In `Utils` I have two files: `demographics2.owl` and `nidm-experiment.owl` (see [here](https://github.com/incf-nidash/PyNIDM/blob/master/nidm/experiment/Utils.py#L361)). I need to know where I can find them in  `nidm-specs` and I couldn't find them in `nidm-specs/nidm/nidm-experiment/imports/`.

**Comment by khelm** [comment]
The files in the imports directory are terms that we are importing from different ontologies.  The actual nidm.owl file is actually in the `/nidm-experiment/terms`

**Comment by dbkeator** [comment]
I've removed demographics2.owl from the Util.py load_nidm_owl_files function.  See [https://github.com/incf-nidash/PyNIDM/pull/96](url)
